name: Extract Game Assets

on:
  workflow_dispatch: # Allows manual trigger
  push:
    paths:
      - 'client/public/dyna.zip'  # Updated path to match repo structure
    branches: [main]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          
      - name: Install dependencies
        run: pip install pillow tqdm  # Added tqdm
          
      - name: Extract assets
        run: python scripts/extract_assets.py client/public/dyna.zip client/public/game_assets
        env:
          PYTHONUNBUFFERED: 1  # For real-time logs
          
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: game-assets
          path: client/public/game_assets
          retention-days: 3  # Automatically delete after 3 days
