name: Extract Game Assets

on:
  workflow_dispatch:
  push:
    paths:
      - 'public/dyna.zip'
    branches: [main]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow tqdm
          
      - name: Create output directory
        run: mkdir -p public/game_assets
        
      - name: Extract assets
        run: python scripts/extract_assets.py public/dyna.zip public/game_assets
        env:
          PYTHONUNBUFFERED: 1  # For real-time logs
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: game-assets
          path: public/game_assets
          retention-days: 1
